services:
  postgres:
    image: postgres:13
    restart: always
    container_name: db-postgres-task
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my-weak-password 
    volumes:
      - ./data:/var/lib/postgresql/data